### ISSUE TITLE
How install on Arch Linux/Manjaro?

### ISSUE THREAD

**Issue by RenanRischiotto** [gsteph/groove-dl#28]
Hello!

I use Manjaro, which is based on Arch Linux, and I do not know how to install, since there are only instructions for Debian, Red Hat and derivatives on the site. I have already installed the the latest version of "wxgtk", "setuptools" and the python of course (came already installed), but still got no success when running "sudo python setup.py install" command inside the folder "ObjectListView". Could anyone help me?

Hugs!

**Comment by gsteph** [comment]
What error are you getting? You might not have sudo so just login as root then execute the same command without sudo.

**Comment by RenanRischiotto** [comment]
Thanks for the reply, I ran without "sudo" and the error persists: 

renan@manjaro ObjectListView-1.2]$ su
Senha:
[root@manjaro ObjectListView-1.2]# python setup.py install
  File "setup.py", line 58
    print "To build an egg setuptools must be installed"
                                                       ^
SyntaxError: invalid syntax

**Comment by gsteph** [comment]
Makes sense now. Install python2 and run the same command using it.
groove-dl too is written in python2.

**Comment by RenanRischiotto** [comment]
It worked, but now when I run the command to start the program, the following error is shown:

[renan@Manjaro groove-dl] $ python2 groove.py
Traceback (most recent call last):
   File "groove.py", line 190, in < module >
     import gui
   File "/home/renan/Documents/groove-dl/gui.py", line 48, in < module >
     import wx
ImportError: No module named wx

**Comment by gsteph** [comment]
Install wxPython for python2.

**Comment by cirrusUK** [comment]
i just installed this using the AUR pkg, the pkgbuild pulls in Packages (1) wxpython-3.0.2.0-1
 but you will have to install the python2-objectlistview dep from aur also.
i cant seem to figure out how to launch the TUI version ?

**Comment by gsteph** [comment]
Just type your query as a command line argument and it won't launch the GUI.
groove-dl <search query>
