### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by eerie** [gsteph/groove-dl#34]
Executing grrove-dl I get this error:

Initializing...
Traceback (most recent call last):
  File "/usr/share/groove-dl/groove.py", line 195, in <module>
    getToken() #Get a static token
  File "/usr/share/groove-dl/groove.py", line 64, in getToken
    _token = json.JSONDecoder().decode(gzip.GzipFile(fileobj=(StringIO.StringIO(conn.getresponse().read()))).read())["result"]
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by gsteph** [comment]
Grooveshark is shutdown. Haven't you heard?

**Comment by eerie** [comment]
sorry, I wasn't aware yet.
